# Generated by Django 6.0.3 on 2026-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
