# Generated by Django 6.0.3 on 2026-06-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applianceschedule_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceschedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
