# Generated by Django 6.0.3 on 2026-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_applianceschedule_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='claim_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='claim_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_secret_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
