# Generated by Django 6.0.3 on 2026-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='alert_type',
            field=models.CharField(choices=[('undervoltage', 'Undervoltage'), ('overvoltage', 'Overvoltage'), ('overcurrent', 'Overcurrent'), ('overload', 'Overload')], max_length=50),
        ),
    ]
