# Generated by Django 6.0.3 on 2026-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_safetyalert_is_resolved_safetyalert_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceschedule',
            name='repeat_pattern',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='none', max_length=20),
        ),
    ]
