# Generated by Django 6.0.3 on 2026-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_applianceschedule_repeat_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceschedule',
            name='repeat_pattern',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
