# Generated by Django 6.0.3 on 2026-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_applianceschedule_repeat_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceschedule',
            name='repeat_pattern',
            field=models.CharField(choices=[('none', 'None - runs once only'), ('daily', 'Daily - repeats every day at same time')], default='none', max_length=20),
        ),
    ]
